sudo: false
language: cpp
addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
script: make
env:
  - MY_CXX=g++-5
  - MY_CXX=clang++
install:
  - export CXX="${MY_CXX}"
